# Generated by Django 5.1.15 on 2026-03-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='periodicity',
            field=models.CharField(choices=[('FULL TIME', 'Temps plein'), ('PART TIME', 'Temps partiel')], default='FULL TIME', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='remote_status',
            field=models.CharField(choices=[('HYBRID', 'Hybride'), ('FULL REMOTE', 'Télétravail complet'), ('ON SITE', 'Sur site')], default='ON SITE', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='source_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
