# Generated by Django 5.2.7 on 2026-02-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500)),
                ('record_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('PROCESSED', 'Traité'), ('ERROR', 'Erreur')], default='PENDING', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField(blank=True)),
            ],
        ),
    ]
