# Generated by Django 5.1.15 on 2026-03-10 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedInScrapingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('url_not_found', 'URL introuvable'), ('scraping', 'En cours de scraping'), ('done', 'Terminé'), ('error', 'Erreur')], default='pending', max_length=20)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('scraped_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scraping_task', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LinkedIn Scraping Task',
                'verbose_name_plural': 'LinkedIn Scraping Tasks',
            },
        ),
    ]
