# Generated by Django 5.1.15 on 2026-03-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
