# Generated by Django 5.1.15 on 2026-03-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0002_remove_promotion_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='label',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
