# Generated by Django 5.1.15 on 2026-03-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0003_alter_promotion_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
